version: '3.4'

services:
  node:
    container_name: {{projectName}}_node_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    ports:
      - "8089:8089"
    volumes:
      - .:/usr/app:cached
    networks:
     - {{projectName}}_net
{{#ifEquals orm "Mongoose" }}
  db:
    container_name: {{projectName}}_db_1
    restart: always
    build:
      context: docker/mongo/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
     - {{projectName}}_net
    environment:
      MONGODB_ROOT_PASSWORD: 123456
      MONGODB_USERNAME: {{projectName}}
      MONGODB_PASSWORD: {{projectName}}123
      MONGODB_DATABASE: db_{{projectName}}
    volumes:
      - data:/bitnami/mongodb {{/ifEquals}} {{#ifEquals orm "TypeORM" }}

  db:
    container_name: {{projectName}}_db_1
    restart: always
    build:
      context: docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER={{projectName}}
      - POSTGRES_DB=db_{{projectName}}
      - POSTGRES_PASSWORD={{projectName}}123
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - {{projectName}}_net {{/ifEquals}} {{#ifEquals orm "MikroORM" }}

  db:
    container_name: {{projectName}}_db_1
    restart: always
    build:
      context: docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER={{projectName}}
      - POSTGRES_DB=db_{{projectName}}
      - POSTGRES_PASSWORD={{projectName}}123
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - {{projectName}}_net {{/ifEquals}}

  mail:
    container_name: {{projectName}}_mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
     - {{projectName}}_net

  minio:
    container_name: {{projectName}}_minio_1
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
     - {{projectName}}_net
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_DOMAIN: localhost
    volumes:
      - minio:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data

  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: {{projectName}}_redis_1
    environment:
      - REDIS_PASSWORD=ewsua132435 # Security reasons
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG # Security reasons
    ports:
      - "6379:6379"
    networks:
     - {{projectName}}_net
    volumes:
      - redis:/bitnami/redis/data

networks:
  {{projectName}}_net:
    driver: "bridge"

volumes:
  data:
    driver: "local"
  minio:
    driver: "local"
  redis:
    driver: "local"
